blubbtest_homepage:
    pattern:  /default/{name}
    defaults: { _controller: BlubbtestBundle:Default:index }

blubbuser_crud:
    resource: "@BlubbtestBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /
