parameters:
#    blubbtest.example.class: Blubb\testBundle\Example

services:
#    blubbtest.example:
#        class: %blubbtest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
